### ISSUE TITLE
Virtual Register Values need to be saved into the database

### ISSUE THREAD

**Issue by aadabi** [seadsystem/Backend#12]
Check out live feed from 
http://96.249.206.209
Go to settings:
http://96.249.206.209/settings.html
There are two useful Virtual Register values : Net metering and consumption
The two Virtual registers need to be saved into the Database. I could not find them in the DB.

**Comment by iangudger** [comment]
Virtual Register data should be calculable from the data recorded from the physical registers. Storing calculable data is frowned upon in the relational model.

**Comment by aadabi** [comment]
Good point, wrote some code that does the aggregation in python. It would have been very convenient to get the data directly but not needed anymore. 120MB per 38 hours  at this rate we will have 8.185263 GB per month. and extra cost of adding on virtual registers is 1.6MB per 38 hours 109MB per month.
