### ISSUE TITLE
Test breakage at head

### ISSUE THREAD

**Issue by iangudger** [seadsystem/Backend#27]
There is a spelling error here:
https://github.com/seadsystem/Backend/blob/master/DB/landingzone/database/database_test.go#L101

stetement is spelled wrong. This was fixed upstream with https://github.com/DATA-DOG/go-sqlmock/commit/f191e8603617b8de5cff91e17997d5eada180133 which broke our test.

**Comment by nsokolnikov** [comment]
Fixed.
